#%RAML 1.0 DataType

uses:
  prelude: /libraries/prelude.raml
  core: /libraries/core.raml

(prelude.common):
displayName: Push
description: |
  A [Web Push](https://developer.mozilla.org/en-US/docs/Web/API/Push_API) notifier.
type: core.Channel
properties:
  type:
    enum: [push]
