#%RAML 1.0 DataType

uses:
  prelude: /libraries/prelude.raml
  core: /libraries/core.raml

(prelude.common):
displayName: Webhook
description: |
  An outgoing webhook notifier.
type: core.Channel
properties:
  type:
    enum: [webhook]
