#%RAML 1.0 DataType

uses:
  prelude: /libraries/prelude.raml
  core: /libraries/core.raml

(prelude.common):
(core.fieldDescriptions): !include /documentation/fieldDescriptions/service/cloudwatch.yml
displayName: AWS CloudWatch
description: |
  An [AWS CloudWatch](https://aws.amazon.com/cloudwatch/) service. This watchdog
  will monitor the `StatusCheckFailed` metric of an AWS EC2 instance reported by
  AWS CloudWatch.
type: core.Service
properties:
  type:
    enum: [cloudwatch]
  instance_id: string
  region: core.CLOUDWATCH_REGION
