#%RAML 1.0 DataType

uses:
  prelude: /libraries/prelude.raml
  core: /libraries/core.raml

(prelude.common):
displayName: Manual
description: |
  A manually updated watchdog.
type: core.Service
properties:
  type:
    enum: [manual]
  state: core.integer-state-or-pending
  semantic:
    (core.expandable):
    type: nil | core.ObjectId | semantic.Semantic
