#%RAML 1.0 DataType

uses:
  prelude: /libraries/prelude.raml
  core: /libraries/core.raml

(prelude.common):
(core.fieldDescriptions): !include /documentation/fieldDescriptions/service/webhook.yml
displayName: Webhook
description: |
  A [webhook](https://hund.io/help/integrations/webhooks) service.
type: [core.Service, core.HAL/Linkable]
properties:
  type:
    enum: [webhook]
  webhook_key: string
  _links?:
    properties:
      webhook: core.HAL/Link
