#%RAML 1.0 DataType

uses:
  prelude: /libraries/prelude.raml
  core: /libraries/core.raml

(prelude.common):
displayName: Webhook
description: |
  Webhook notifier channel creation form.
type: core.Form
properties:
  type:
    enum: [webhook]
