#%RAML 1.0 DataType

uses:
  core: /libraries/core.raml
  service: /libraries/service.raml

(core.fieldDescriptions): !include /documentation/fieldDescriptions/watchdog.yml
description: |
  The Watchdog creation form object.
type: core.Form
properties:
  high_frequency?:
    type: boolean
    default: false
  service: service.Form/Watchdog/Create
