#%RAML 1.0 DataType

uses:
  prelude: /libraries/prelude.raml
  core: /libraries/core.raml

(prelude.common):
(core.fieldDescriptions): !include /documentation/fieldDescriptions/invitation.yml
displayName: Invitation
description: |
  Invitation update form.
type: core.Form
properties:
  roles?: core.ObjectId[]
