#%RAML 1.0 DataType

uses:
  prelude: /libraries/prelude.raml
  core: /libraries/core.raml

(prelude.common):
displayName: Manual
description: |
  Manual service update form.
type: core.Form
properties:
  state?: core.integer-state-or-pending
  semantic?: nil | core.ObjectId
