#%RAML 1.0 DataType

uses:
  prelude: /libraries/prelude.raml
  core: /libraries/core.raml
  template: /libraries/issue_template/application.raml

(prelude.common):
displayName: Issue
description: |
  Issue cancellation form.
type: core.Form
properties:
  body?:
    description: |
      An optional Issue Update body describing the cancellation.
    type: core.i18n-string
  template?:
    description: |
      An optional Issue Template which will create an Issue Update describing
      the cancellation. This field takes precedence over `body`.
    type: core.ObjectId | template.IssueTemplate/Application/Form/Create
