#%RAML 1.0 DataType

uses:
  prelude: /libraries/prelude.raml
  core: /libraries/core.raml
  schedule: /libraries/schedule.raml

(prelude.common):
(core.fieldDescriptions): !include /documentation/fieldDescriptions/issue.yml
displayName: Issue
description: |
  Issue creation form.
type: core.Form
properties:
  title: string
  body: string
  label?:
    type: nil | core.ISSUE_LABEL
    default: null
  state_override?:
    type: nil | core.integer-state
    default: null
  priority?:
    type: core.ISSUE_PRIORITY
    default: 0
  open_graph_image_url?: core.maybe-string
  schedule?: schedule.Schedule/Form/Create
  components: core.ObjectId[]
