#%RAML 1.0 DataType

uses:
  prelude: /libraries/prelude.raml
  core: /libraries/core.raml
  schedule: /libraries/schedule.raml

(prelude.common):
(core.fieldDescriptions): !include /documentation/fieldDescriptions/issue.yml
displayName: Issue
description: |
  Issue update form.
type: core.Form
properties:
  title?: string
  body?: string
  label?: core.ISSUE_LABEL
  state_override?: nil | core.integer-state
  priority?: core.ISSUE_PRIORITY
  open_graph_image_url?: core.maybe-string
  schedule?: schedule.Schedule/Form/Update
  components?: core.ObjectId[]
  began_at?:
    (core.overrideFieldDescription):
    description: |
      When given, backdates the beginning of this issue to the provided time.

      **Note:** This value cannot be set into the future, nor any time that would
      encroach upon any Update's `effective_after` time.

      **Note:** `began_at` cannot be updated if this Issue is scheduled; you
      must instead revise the `schedule` object itself to change the automatic
      begin/end times of the Issue.
    type: core.timestamp
