#%RAML 1.0 ResourceType

type:
  core.simple-action:
    displayName: <<displayName>>
    description: <<description>>
    idPrefix: <<idPrefix>>
    itemType: <<itemType>>
    successDescription: <<successDescription>>
    notFoundDescription: <<notFoundDescription>>
    responseExample: <<responseExample>>
    errorNotFoundExample: <<errorNotFoundExample>>
    errorNotAuthorizedExample: <<errorNotAuthorizedExample>>
put:
  body:
    application/json:
      examples:
        "PUT <<resourcePath>>": <<requestExample>>
      type: <<paramsType>>
