#%RAML 1.0 ResourceType

uriParameters:
  <<idPrefix>>_id:
    description: |
      The ObjectId of the of the <<idPrefix|!uppercamelcase>>.
    type: core.ObjectId
put:
  is:
  - core.not-found-failable:
      errorNotFoundExample: <<errorNotFoundExample>>
  displayName: <<displayName>>
  description: <<description>>
  body:
    application/json:
      examples:
        "PUT <<resourcePath>>": <<requestExample>>
      type: <<paramsType>>
  responses:
    200:
      description: <<successDescription>>
      body:
        application/hal+json:
          examples:
            "PUT <<resourcePath>> (200)": <<responseExample>>
          type: <<itemType>>
    404:
      description: <<notFoundDescription>>
