#%RAML 1.0 ResourceType

type:
  core.read-collection:
    getResponseExample: <<getResponseExample>>
    itemType: <<itemType>>
post:
  is:
  - core.not-authorized-failable:
      permissionLevel: write
      errorNotAuthorizedExample: <<errorNotAuthorizedExample>>
  - core.validation-failable:
      errorExample: <<postErrorExample>>
  displayName: Create a <<resourcePathName|!singularize|!uppercamelcase>>
  description: |
    Create a new <<resourcePathName|!uppercamelcase|!singularize>>. Returns the newly created <<resourcePathName|!uppercamelcase|!singularize>>.
  body:
    application/json:
      type: <<postParamsType>>
      examples:
        "POST <<resourcePath>>": <<postRequestExample>>
  responses:
    201:
      (specs.requestBody): auto:<<resourcePathName|!singularize>>
      description: |
        Successfully created a new <<resourcePathName|!uppercamelcase|!singularize>>.
      body:
        application/hal+json:
          type: <<itemType>>
          examples:
            "POST <<resourcePath>> (201)": <<postResponseExample>>
    400:
      (specs.requestBody): "{}"
      description: |
        Failed to create a new <<resourcePathName|!uppercamelcase|!singularize>>.
