#%RAML 1.0 ResourceType

type:
  core.read-collection-item:
    errorNotFoundExample: <<errorNotFoundExample>>
    getResponseExample: <<getResponseExample>>
    itemType: <<itemType>>
    idPrefix: <<idPrefix>>
put:
  is:
  - core.not-authorized-failable:
      permissionLevel: write
      errorNotAuthorizedExample: <<errorNotAuthorizedExample>>
  - core.validation-failable:
      errorExample: <<putErrorExample>>
  displayName: Update a <<resourcePathName|!singularize|!uppercamelcase>>
  description: |
    Update the given <<resourcePathName|!uppercamelcase|!singularize>> by ObjectId.
  body:
    application/json:
      examples:
        "PUT <<resourcePath>>": <<putRequestExample>>
      type: <<putParamsType>>
  responses:
    200:
      (specs.bindIds):
        <<resourcePathName|!singularize>>: auto
      (specs.requestBody): auto:<<resourcePathName|!singularize>>
      description: |
        Successfully updated <<resourcePathName|!uppercamelcase|!singularize>>.
      body:
        application/hal+json:
          examples:
            "PUT <<resourcePath>> (200)": <<putResponseExample>>
          type: <<itemType>>
    400:
      (specs.bindIds):
        <<resourcePathName|!singularize>>: auto
      description: |
        Failed to update <<resourcePathName|!uppercamelcase|!singularize>>.
    403:
      (specs.bindIds):
        <<resourcePathName|!singularize>>: auto
    404:
      (specs.requestBody): auto:<<resourcePathName|!singularize>>
delete?:
  is:
  - core.not-authorized-failable:
      permissionLevel: write
      errorNotAuthorizedExample: <<errorNotAuthorizedExample>>
  displayName: Delete a <<resourcePathName|!singularize|!uppercamelcase>>
  description: |
    Delete the given <<resourcePathName|!uppercamelcase|!singularize>> by ObjectId.
  responses:
    204:
      (specs.bindIds):
        <<resourcePathName|!singularize>>: auto
      description: |
        Successfully deleted <<resourcePathName|!uppercamelcase|!singularize>>.
    403:
      (specs.bindIds):
        <<resourcePathName|!singularize>>: auto
