#%RAML 1.0 ResourceType

description: Collection of <<resourcePathName>> in this context.
get:
  displayName: Get All <<resourcePathName|!uppercamelcase>>
  description: |
    Index of <<resourcePathName|!uppercamelcase>> collection. Returns a PagedArray.
  queryParameters:
    limit?:
      description: |
        The number of <<resourcePathName|!uppercamelcase>> to return per page.
      default: 10
      type: integer
      minimum: 1
      maximum: 100
      example: 3
    starting_after?:
      description: |
        A <<resourcePathName|!uppercamelcase|!singularize>> ObjectId after which the returned array of
        <<resourcePathName|!uppercamelcase>> will begin in descending order.
        Typically, this is used to retrieve the next page of <<resourcePathName|!uppercamelcase>>
        in descending order.
      type: core.ObjectId
    ending_before?:
      description: |
        A <<resourcePathName|!uppercamelcase|!singularize>> ObjectId before which the returned array of
        <<resourcePathName|!uppercamelcase>> will end in descending order.
        Typically, this is used to retrieve the previous page of <<resourcePathName|!uppercamelcase>>
        in descending order.
      type: core.ObjectId
  responses:
    200:
      (specs.createModels):
        <<resourcePathName|!singularize>>:
          count: 5
      description: |
        Successfully retrieved index.
      body:
        application/hal+json:
          examples:
            "GET <<resourcePath>> (200)": <<getResponseExample>>
          type: core.PagedArray
          properties:
            data: <<itemType>>[]
            _links?:
              properties:
                create-form?: core.HAL/Link
