#%RAML 1.0 DataType

uses:
  prelude: /libraries/prelude.raml
  core: /libraries/core.raml

(prelude.common):
(core.fieldDescriptions): !include /documentation/fieldDescriptions/service/updown.yml
displayName: Updown
description: |
  Updown service creation form.
type: core.Form
properties:
  type:
    enum: [updown]
  monitor_api_key: string
  monitor_token: string
