#%RAML 1.0 Library

usage: |
  Defines Group type and forms.

types:
  Group: !include /types/state/group.raml
  Group/Form/Create: !include /types/state/group/form/create.raml
  Group/Form/Update: !include /types/state/group/form/update.raml
