#%RAML 1.0 Library

usage: |
  Defines Invitation type and forms.

types:
  Invitation: !include /types/state/invitation.raml
  Invitation/Form/Create: !include /types/state/invitation/form/create.raml
  Invitation/Form/Update: !include /types/state/invitation/form/update.raml
