#%RAML 1.0 Library

usage: |
  Defines MetricProvider type and forms.

types:
  MetricProvider: !include /types/state/metric_provider.raml
  MetricProvider/Form/Create: !include /types/state/metric_provider/form/create.raml
  MetricProvider/Form/Update: !include /types/state/metric_provider/form/update.raml
