#%RAML 1.0 Library

usage: |
  Defines Notifier types and forms.

types:
  Notifier: !include /types/state/notifier.raml
  Notifier/Form/Create: !include /types/state/notifier/form/create.raml
  Notifier/Form/Update: !include /types/state/notifier/form/update.raml
