#%RAML 1.0 Library

usage: |
  Defines the Issue Schedule type and forms.

types:
  Schedule: !include /types/state/schedule.raml
  Schedule/Form/Create: !include /types/state/schedule/form/create.raml
  Schedule/Form/Update: !include /types/state/schedule/form/update.raml
