#%RAML 1.0 Library

usage: |
  Defines Semantic type and forms.

types:
  Semantic: !include /types/state/semantic.raml
  Semantic/Form/Create: !include /types/state/semantic/form/create.raml
  Semantic/Form/Update: !include /types/state/semantic/form/update.raml
