#%RAML 1.0 Library

usage: |
  Defines Subscription types and forms.

types:
  Subscription: !include /types/state/subscription.raml
  Subscription/Form/Create: !include /types/state/subscription/form/create.raml
  Subscription/Form/Update: !include /types/state/subscription/form/update.raml
