#%RAML 1.0 DataType

uses:
  prelude: /libraries/prelude.raml
  core: /libraries/core.raml

(prelude.common):
displayName: Push
description: |
  Web Push notifier channel update form.
type: core.Form
