#%RAML 1.0 DataType

uses:
  core: /libraries/core.raml

displayName: Check
description: |
  A Hund Native Monitoring Check.
type: object
additionalProperties: false
properties:
  method: string
  target: string
  regions: core.NATIVE_REGION[]
  frequency: integer
  timeout: integer
  consecutive_check_degraded_threshold: core.nonnegative-integer?
  consecutive_check_outage_threshold: core.nonnegative-integer
  percentage_regions_failed_threshold: core.percentage
