#%RAML 1.0 DataType

uses:
  prelude: /libraries/prelude.raml
  core: /libraries/core.raml

(prelude.common):
(core.fieldDescriptions): !include /documentation/fieldDescriptions/service/newrelic.yml
displayName: New Relic
description: |
  New Relic service creation form.
type: core.Form
properties:
  api_key: string
  api_region?:
    type: core.NEWRELIC_API_REGION
    default: us
  suppress_warning_violations?:
    type: boolean
    default: false
  suppress_future_issues?:
    type: boolean
    default: false
  issue_templates?:
    type: core.WatchdogIssueTemplates
    default: { outage: null, degraded: null, operational: null }
  alert_policies: string[]
