#%RAML 1.0 DataType

uses:
  prelude: /libraries/prelude.raml
  core: /libraries/core.raml

(prelude.common):
(core.fieldDescriptions): !include /documentation/fieldDescriptions/subscription/webhook.yml
displayName: Webhook
description: |
  A webhook Subscription channel update form.
type: core.Form
properties:
  url?: string
  verb?: core.WEBHOOK_VERB
