#%RAML 1.0 DataType

uses:
  prelude: /libraries/prelude.raml
  core: /libraries/core.raml
  channel: /libraries/channel.raml

(prelude.common):
(core.fieldDescriptions): !include /documentation/fieldDescriptions/subscription.yml
displayName: Subscription
description: |
  Subscription creation form.
type: [core.Form, core.NotificationPreferential/Form]
properties:
  channel: channel.Form/Subscription/Create
  notifier: core.ObjectId
  curated?:
    type: boolean
    default: false
  remove_links?:
    type: boolean
    default: false
