#%RAML 1.0 DataType

uses:
  prelude: /libraries/prelude.raml
  core: /libraries/core.raml

(prelude.common):
(core.fieldDescriptions): !include /documentation/fieldDescriptions/subscription/sns.yml
displayName: SMS via AWS SNS
description: |
  An SNS Subscription channel update form.
type: core.Form
properties:
  phone?: core.SNS_PHONE_NUMBER
