#%RAML 1.0 DataType

uses:
  core: /libraries/core.raml
  native: /libraries/service/native.raml

displayName: HTTP
description: |
  Hund Native Monitoring HTTP Check creation form.
type: native.Check/Form/Update
properties:
  username?: core.maybe-string
  password?: core.maybe-string
  response_body_must_contain?: core.maybe-string
  response_body_must_contain_mode?: core.NATIVE_STRING_CONTAINMENT_MODE
  response_code_must_be?: nil | integer
  headers?: native.HTTP/Headers
  follow_redirects?: boolean
  ssl_verify_peer?: boolean
