#%RAML 1.0 DataType

uses:
  prelude: /libraries/prelude.raml
  core: /libraries/core.raml
  watchdog: /libraries/watchdog.raml

(prelude.common):
(core.fieldDescriptions): !include /documentation/fieldDescriptions/component.yml
description: |
  Component creation form.
type: core.Form
properties:
  name: core.i18n-string
  description?: core.maybe-i18n-string
  exclude_from_global_uptime?:
    type: boolean
    default: false
  exclude_from_global_history?:
    type: boolean
    default: false
  group: core.ObjectId
  watchdog: watchdog.Watchdog/Form/Create
