#%RAML 1.0 DataType

uses:
  prelude: /libraries/prelude.raml
  core: /libraries/core.raml
  event: /libraries/event/core.raml
  component: /libraries/component.raml

(prelude.common):
(core.fieldDescriptions): !include /documentation/fieldDescriptions/event.yml
displayName: ComponentEvented
type: event.Event
discriminatorValue: component_evented
properties:
  eventable:
    (core.expandable):
    type: core.ObjectId | component.Component
  context: event.EmptyContextual
