#%RAML 1.0 DataType

uses:
  prelude: /libraries/prelude.raml
  core: /libraries/core.raml
  event: /libraries/event/core.raml
  metric_provider: /libraries/metric_provider.raml

(prelude.common):
(core.fieldDescriptions): !include /documentation/fieldDescriptions/event.yml
displayName: MetricProviderEvented
type: event.Event
discriminatorValue: metric_provider_evented
properties:
  eventable:
    (core.expandable):
    type: core.ObjectId | metric_provider.MetricProvider
  context: event.EmptyContextual
