#%RAML 1.0 DataType

uses:
  prelude: /libraries/prelude.raml
  core: /libraries/core.raml
  variables: /libraries/issue_template/variables.raml

(prelude.common):
(core.fieldDescriptions): !include /documentation/fieldDescriptions/issue_template.yml
displayName: IssueTemplate
description: |
  IssueTemplate update form.
type: core.Form
properties:
  name?: string
  title?: core.i18n-string
  label?: core.ISSUE_TEMPLATE_LABEL
  body?: core.i18n-string
  variables?: variables.IssueTemplateVariables/Form
