#%RAML 1.0 DataType

uses:
  prelude: /libraries/prelude.raml
  core: /libraries/core.raml

(prelude.common):
(core.fieldDescriptions): !include /documentation/fieldDescriptions/update.yml
displayName: Update
description: |
  Issue Updates update form.
type: core.Form
properties:
  body?: core.maybe-string
  label?: nil | core.UPDATE_LABEL
  state_override?: nil | core.integer-state
  effective_after?:
    (core.overrideFieldDescription):
    description: |
      Backdate this Update to be effective on its Issue after the given time,
      until the `effective_after` time of the Update succeeding this one, if
      one exists.

      **Note:** This field cannot be set into the future, nor made to encroach
      upon the `effective_after` time of the updates preceding or succeeding
      this one (`updates` on an Issue must occur in proper reverse-chronological
      order according to their `effective_after` fields).
    type: core.timestamp
