#%RAML 1.0 DataType

uses:
  prelude: /libraries/prelude.raml
  core: /libraries/core.raml
  native: /libraries/service/native.raml

(prelude.common):
(core.fieldDescriptions): !include /documentation/fieldDescriptions/service/native/check.yml
displayName: ICMP
description: |
  Hund Native Monitoring ICMP Check update form.
type: native.Check/Form/Update
properties:
  percentage_failed_threshold?: core.percentage
  ip_version?: core.NATIVE_IP_VERSION
